# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'docker-test:$(build.buildId)'

steps:
- script: docker build -f Dockerfile -t $(imageName) .
  displayName: 'docker build'
- script: docker login -u RCGLabACR -p FhrhyRug25e031=Nfqcmti9TdGu10hs2 rcglabacr.azurecr.io
- script: docker push rcglabacr.azurecr.io/$(imageName)
