# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'azure-test:v1'

steps:
  - script: docker build -t https://cloud.docker.com/repository/docker/bergerinc/$(imageName) .
  - script: docker login -u bergerinc -p 24nono55 https://cloud.docker.com/repository/docker/bergerinc
  - script: docker push https://cloud.docker.com/repository/docker/bergerinc/$(imageName)
